### ISSUE TITLE
Running Differently by CRON vs CLI

### ISSUE THREAD

**Issue by teddyshithouse** [syeo66/slowplayer#1]
THANKS SO MUCH! 

So I am having an issue where I get clean refreshes when I run via CLI, but when Cron is running the program I get the diagnostic gradients and the triangle & circles in between frames. Any ideas?

Thank you!

**Comment by syeo66** [comment]
Hey there.
It seems you have two different versions of the IT8951 on your Pi. I changed the source code of it to remove the other tests and just leave the image output part. Maybe you need to change the path from `IT8951/IT8951` to the full path (probably `/home/pi/slowplayer/IT8951/IT8951`) to make sure it always takes the correct one.
Let me know if this helps.

**Comment by teddyshithouse** [comment]
I just figured that out and came to remove my bug. 
Thanks for the reply and the code!

**Comment by syeo66** [comment]
Great to hear, thanks.
